"""Phase F: generate results_macros.tex so no number is hand-typed twice.

Every macro here traces to a specific CSV under RTS_Paper/outputs/. Run
after Phases B-E complete. \\input{results_macros} is already referenced
(commented) near the top of the draft.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

ROOT = Path(__file__).resolve().parents[2]
METRICS_DIR = ROOT / "RTS_Paper" / "outputs" / "metrics"
PAPER_DIR = ROOT / "RTS_Paper" / "paper"


def macro_name(*parts: str) -> str:
    # LaTeX macro names must be letters only.
    raw = "".join(parts)
    return "res" + re.sub(r"[^a-zA-Z]", "", raw)


def fmt(x: float, digits: int = 3) -> str:
    return f"{x:.{digits}f}"


def main() -> None:
    lines = ["% Auto-generated by build_macros.py. Do not hand-edit.", ""]

    macro_path = METRICS_DIR / "phase_b_loro_clean_macro.csv"
    if macro_path.exists():
        macro = pd.read_csv(macro_path).set_index("model")
        for model in macro.index:
            tag = model.replace(" ", "")
            for metric in ["precision", "recall", "f1", "fpr", "roc_auc"]:
                mean = macro.loc[model, f"{metric}_mean"]
                std = macro.loc[model, f"{metric}_std"]
                name = macro_name(tag, metric)
                lines.append(f"\\newcommand{{\\{name}}}{{{fmt(mean)}\\pm{fmt(std)}}}")

    payload_path = METRICS_DIR / "payload_model.csv"
    if payload_path.exists():
        payload = pd.read_csv(payload_path)
        row128 = payload[(payload.feature_budget == "128") & (payload.representation == "32-bit float")].iloc[0]
        row16 = payload[(payload.feature_budget == "16") & (payload.representation == "32-bit float")].iloc[0]
        lines.append(f"\\newcommand{{\\respayloadonetwoeight}}{{{int(row128.payload_bytes_per_record)}}}")
        lines.append(f"\\newcommand{{\\respayloadsixteen}}{{{int(row16.payload_bytes_per_record)}}}")

    latency_path = METRICS_DIR / "latency_and_envelope_verdicts.csv"
    if latency_path.exists():
        lat = pd.read_csv(latency_path)
        e2e = lat[lat.stage == "end_to_end"]
        for _, row in e2e.iterrows():
            tag = row["model"].replace(" ", "")
            lines.append(f"\\newcommand{{\\{macro_name(tag,'p95latency')}}}{{{fmt(row['p95_ms'],2)}}}")

    shap_path = METRICS_DIR / "shap_timing.csv"
    if shap_path.exists():
        shap_df = pd.read_csv(shap_path).set_index("model")
        for model in shap_df.index:
            tag = model.replace(" ", "")
            lines.append(f"\\newcommand{{\\{macro_name(tag,'shapexplainmedian')}}}{{{fmt(shap_df.loc[model,'explain_only_median_ms'],2)}}}")
            lines.append(f"\\newcommand{{\\{macro_name(tag,'shapexplainpersec')}}}{{{fmt(shap_df.loc[model,'explanations_per_sec'],2)}}}")

    out_path = PAPER_DIR / "results_macros.tex"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
